language: php

php:
  - 5.5

env:
  - DB=mysql

before_script:
  - mysql -e 'create database revive_test; use revive_test; source db.sql;'
  - mv .env.example .env

install:
   - composer update
   - composer install --dev --prefer-source --no-interaction

script: phpunit --configuration phpunit.xml --coverage-text
